package org.zoodb.test.jdo;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)

@Suite.SuiteClasses({
   org.zoodb.test.jdo.Test_010_DbAdmin.class,
   Test_011_DbAdminInMemory.class,
   Test_012_DbAdminCheckDb.class,
   Test_013_DbAdminZooDebug.class,
   Test_014_XmlImportExport.class,
   Test_015_DatabaseComparison.class,
   Test_016_DbAdminZooQuery.class,
   Test_020_Session.class,
   Test_021_MultiSession.class,
   Test_022_MultiSessionSchema.class,
   Test_023_GenericObjects.class,
   Test_024_MultiSessionConcurrency.class,
   Test_025_SingleSessionConcurrency.class,
   Test_026_OsgiSession.class,
   Test_030_Schema.class,
   Test_031_SchemaReading.class,
   Test_032_SchemaRenaming.class,
   Test_033_SchemaDefinition.class,
   Test_034_SchemaEvolution.class,
   Test_035_SchemaEvolutionShorts.class,
   Test_036_SchemaInstanceHandling.class,
   Test_037_SchemaWriting.class,
   Test_038_SchemaAutoCreate.class,
   Test_039_SchemaEvolBug.class,
   Test_040_Transactions.class,
   Test_041_TransactionsCommit.class,
   Test_042_TransactionsEvict.class,
   Test_043_TransactionsTransient.class,
   Test_044_TransactionsSynchronization.class,
   Test_045_TransactionsCallBacks.class,
   Test_046_TransactionsLifecycleListener.class,
   Test_047_TransactionsManagedObjects.class,
   Test_048_TransactionsOptions.class,
   Test_050_ObjectCreation.class,
   Test_060_Extents.class,
   Test_061_ExtentDeletion.class,
   Test_062_ExtentIteration.class,
   Test_070_Query.class,
   Test_070i_Query.class,
   Test_070ii_Query.class,
   Test_071_QueryExamples.class,
   Test_072_PolePosBarcelonaQuery.class,
   Test_073_PolePosBarcelonaDelete.class,
   Test_074_QueryComplex.class,
   Test_080_Serialization.class,
   Test_080m_SerializationInMemory.class,
   Test_081_SerializationBugs.class,
   Test_082_SerializationBugs.class,
   Test_083_SerializationBugs.class,
   Test_083_SerializationDbCollections.class,
   Test_084_SerializationBugs.class,
   Test_084_SerializationBugRefToPM.class,
   Test_090_IndexManagement.class,
   Test_091_IndexUpdates.class,
   Test_100_FreeSpaceManager.class,
   Test_101_DbSpaceManagement.class,
   Test_110_Concurrency.class,
   Test_120_QuerySetResult.class,
   Test_121_QueryResultProcessing.class,
   Test_122_QueryBugs.class,
   Test_123_QueryExtentAdaptor.class,
   Test_124_QueryCache.class,
   Test_125_QueryOnCandidates.class,
   Test_126_QueryOrderBy.class,
   Test_126i_QueryOrderBy.class,
   Test_127_QueryBoolFunctions.class,
   Test_128_QueryPath.class,
   Test_128i_QueryPath.class,
   Test_129_QueryNonBoolFunctions.class,
   Test_130_DetachAllOnCommit.class,
   Test_140_TxOptimistic.class,
   Test_150_TxNonTxRead.class,
   Test_160_SchemaBug.class,
   Test_170_QuerySetRange.class,
   Test_171_QueryBug096.class,
   Test_172_QueryStatistics.class,
   Test_173_QueryIssue99_100_104.class
})

public class TestSuite {

}
